-- V10: añade 8 columnas de tracking a METRICAS (idempotente).
-- En la BD de desarrollo estas columnas ya existen (aplicadas manualmente
-- durante la resolución de V9). En entornos limpios se crean aquí.

SET @db = DATABASE();

SET @q = (SELECT IF(COUNT(*) = 0,
    'ALTER TABLE METRICAS ADD COLUMN personas_unicas INT NULL',
    'DO 0')
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'METRICAS' AND COLUMN_NAME = 'personas_unicas');
PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;

SET @q = (SELECT IF(COUNT(*) = 0,
    'ALTER TABLE METRICAS ADD COLUMN tiempo_permanencia_prom DOUBLE NULL',
    'DO 0')
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'METRICAS' AND COLUMN_NAME = 'tiempo_permanencia_prom');
PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;

SET @q = (SELECT IF(COUNT(*) = 0,
    'ALTER TABLE METRICAS ADD COLUMN entradas INT NULL',
    'DO 0')
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'METRICAS' AND COLUMN_NAME = 'entradas');
PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;

SET @q = (SELECT IF(COUNT(*) = 0,
    'ALTER TABLE METRICAS ADD COLUMN salidas INT NULL',
    'DO 0')
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'METRICAS' AND COLUMN_NAME = 'salidas');
PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;

SET @q = (SELECT IF(COUNT(*) = 0,
    'ALTER TABLE METRICAS ADD COLUMN ots_tracking DOUBLE NULL',
    'DO 0')
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'METRICAS' AND COLUMN_NAME = 'ots_tracking');
PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;

SET @q = (SELECT IF(COUNT(*) = 0,
    'ALTER TABLE METRICAS ADD COLUMN velocidad_flujo_prom DOUBLE NULL',
    'DO 0')
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'METRICAS' AND COLUMN_NAME = 'velocidad_flujo_prom');
PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;

SET @q = (SELECT IF(COUNT(*) = 0,
    'ALTER TABLE METRICAS ADD COLUMN tasa_conversion DOUBLE NULL',
    'DO 0')
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'METRICAS' AND COLUMN_NAME = 'tasa_conversion');
PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;

SET @q = (SELECT IF(COUNT(*) = 0,
    'ALTER TABLE METRICAS ADD COLUMN score_compuesto_v2 DOUBLE NULL',
    'DO 0')
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'METRICAS' AND COLUMN_NAME = 'score_compuesto_v2');
PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;
